# Generated by Django 3.1.7 on 2021-07-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('starttime', models.DateTimeField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_todo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Freeboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contents', models.TextField()),
                ('registered_date', models.DateTimeField()),
                ('hits', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'freeboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contents', models.TextField()),
                ('registered_date', models.DateTimeField()),
                ('hits', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'questionboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlinkData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TaskManager.authuser')),
                ('b_time', models.DateTimeField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'blink_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrowsinessData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TaskManager.authuser')),
                ('d_time', models.DateTimeField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'drowsiness_data',
                'managed': False,
            },
        ),
    ]
