# Generated by Django 3.1.7 on 2021-07-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFreeboard',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TaskManager.freeboard')),
                ('uid', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comment_freeboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentQuestionboard',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TaskManager.questionboard')),
                ('uid', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comment_questionboard',
                'managed': False,
            },
        ),
    ]
