# Generated by Django 3.1.7 on 2021-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_commentfreeboard_commentquestionboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('is_complete', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
            ],
            options={
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
