# Generated by Django 3.1.7 on 2021-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(db_column='END_DATE')),
                ('end_time', models.TextField(db_column='END_TIME')),
            ],
            options={
                'db_table': 'complete_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DailyTodo',
        ),
    ]
